package com.tvisha.trooponprime.lib.database.model

data class UnSentMessageModel(
    var platform:Int = 0,
    var access_token:String? = null,
    var reference_id:String?=null,
    var id:Long = 0,
    var message_id:Long = 0,
    var sender_id:Long = 0,
    var receiver_id:Long = 0,
    var message:String? = null,
    var attachment:String? = null,
    var caption:String? =null,
    var message_type:Int=0,
    var is_group:Int=0,
    var is_reply:Int=0,
    var is_forward:Int=0,
    var is_forkout:Int=0,
    var original_message_id:Int=0,
    var is_flag:Int=0,
    var preview_link:String? = null,
    var is_sync : Int= 0,
    var is_read :Int=0,
    var is_delivered : Int=0,
    var status:Int = 0,
    var created_at:String?= null,
    var attachment_downloaded : Int = 0,
    var local_attachment_path:String? = null,
    var sender_uid:String? = null,
    var receiver_uid:String? = null,
)
