package com.tvisha.trooponprime.lib.clientModels

data class ConversationModel(
    var ID: Long = 0,
    var attachment_extension:String? = null,
    var original_message:String? = null,
    var is_forkout:Int =0,
    var is_forward:Int = 0,
    var preview_link:String? = null,
    var status : Int = 0,
    var message_id:Long =0,
    var message:String?=null,
    var sender_id :Long = 0,
    var receiver_id:Long=0,
    var message_type:Int = 0,
    var is_reply:Int = 0,
    var original_message_id:Long = 0,
    var attachment:String?=null,
    var is_read:Int = 0,
    var is_delivered:Int = 0,
    var is_sync:Int = 0,
    var caption:String? = null,
    var is_group:Int = 0,
    var created_at:String?= null,
    var attachment_downloaded:Int = 0,
    var attachment_path:String? = null,
    var member_name:String?=null,
    var is_sender:Int = 0,
    var isSelected:Int = 0,
    var is_like:Int = 0,
    var is_edited:Int = 0,
    var edited_at:String?=null,
    var local_attachment_path:String?=null,
)
